### PR TITLE
Readme Update 2

### PR DESCRIPTION
**Pull request by maityamit**
All Index Add in Redme File

And Work on readme upto Folding Cell 
By Using Hyperlink
Some Images add

Review my Readme FIle
and MERGE the PL

### CODE REVIEW

**Comment by Anni1123** [comment]
This is looking Awesome

**Comment by maityamit** [comment]
> This is looking Awesome

Thank you

**Comment by Anni1123** [comment]
@maityamit Hey, If you want to contribute more in Readme file ? 
Just asking. After all it's your choice only.

**Comment by maityamit** [comment]
Yes .... Just Wait Few Days ..I will send Pull Request

**Comment by maityamit** [comment]
Most Probably Our 12th Exam will cancel.
Please Wait 2/3 days then I will with Full work
Please Just some couple of days ...

**Comment by Anni1123** [comment]
No issues @maityamit .. Take your time ..It's all upto you

**Comment by maityamit** [comment]
Welcome

**Pull request merged**
